site_name: Awesome Python
site_url: https://awesome-python.rdpstudio.top
site_description: A curated list of awesome Python frameworks, libraries and software
site_author: Jack
repo_name: rdp-studio/awesome-python
repo_url: https://github.com/rdp-studio/awesome-python
theme:
  name: material
  palette:
    primary: red
    accent: pink
extra:
  social:
    - type: github
      link: https://github.com/rdp-studio/awesome-python
extra_css:
    - css/extra.css
nav:
  - "Life is short, you need Python.": "index.md"